language: en

pipeline:
- name: SpacyNLP
  model: "en_core_web_sm"
  dimensions: ["LOC", "GPE","DATE"]
- name: SpacyTokenizer
- name: SpacyEntityExtractor
- name: SpacyFeaturizer
  pooling: mean
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 2
- name: DIETClassifier
  epochs: 100

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: FallbackPolicy
    fallback_action_name: 'utter_fallback_default_msg'
    nlu_threshold: 0.7
    core_threshold: 0.7